on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: kbeckenrode/microbiome_ontology:devel
    steps:
      - uses: actions/checkout@v1
#I don't know what should go here, but there was code for open Rstudio. I want to open WebProtege.
      - name: Query dependencies
        run: |
        shell:
    

        
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kbeckenrode/microbiome-ontology
          tag_with_ref: true
          tag_with_sha: true
          tags: latest

      - name: Build pkgdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site(".")'

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
